nombre:  generar  juego pacman 

on: schedule: # Se ejecuta automáticamente cada 24 horas - cron: "0 */24 * * *" workflow_dispatch: # Permite la activación manual push: # Se ejecuta en cada envío a la rama principal branches: - main
   
      
   
   
    
       

trabajos: generar: permisos: contenidos: escribir se ejecuta en: ubuntu-latest minutos de tiempo de espera: 5
  
    
       
     
     

    Pasos: - Nombre: generar pacman-contribution-graph.svg Usos: abozanona/pacman-contribution-graph@main Con: github_user_name: ${{ github.repository_owner }}
         
         
        
             

      # Empuja el SVG generado a la rama de salida - nombre: push pacman-contribution-graph.svg a la rama de salida usa: crazy-max/ ghaction-github-pages@v3.1.0 con: target_branch: output build_dir: dist env: GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
             
         
        
           
           
        
             
